name: wiregistro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # Google Fonts
  google_fonts: ^6.2.1
  
  # UI
  intl: ^0.19.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "web/logo.png"
  web:
    generate: true
    image_path: "web/logo.png"
    background_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "web/logo.png"

flutter:
  uses-material-design: true