name: wiregistro
description: "La mejor app para registrar y dividir gastos con amigos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
# ====== DEPEDENCIAS START ======
  cupertino_icons: ^1.0.8
  
  # ====== FIREBASE ======
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_database: ^12.0.2 
  email_validator: ^3.0.0
  
  # ====== UI/UX ESENCIALES ======
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1
  
  # ====== UTILIDADES ESENCIALES ======
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  
# ====== DEPEDENCIAS END ======

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# ====== CONFIGURACIÓN DE ICONOS (USANDO TU LOGO EXISTENTE) ======
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/logo.png"
  adaptive_icon_background: "#FFD700"
  adaptive_icon_foreground: "web/logo.png"
  
  # Web
  web:
    generate: true
    image_path: "web/logo.png"
    background_color: "#FFD700"
  
  # Windows
  windows:
    generate: true
    image_path: "web/logo.png"

flutter:
  uses-material-design: true
  
  # ====== ASSETS (SOLO TU LOGO EXISTENTE) ======
  assets:
    - web/logo.png